package com.yrx.simple.life.eden.infrastructure.mapper;

import com.yrx.simple.life.eden.infrastructure.po.AntidotePo;
import java.util.List;

public interface AntidotePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antidote
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antidote
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    int insert(AntidotePo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antidote
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    AntidotePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antidote
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    List<AntidotePo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table antidote
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    int updateByPrimaryKey(AntidotePo row);
}