package com.yrx.simple.life.eden.infrastructure.mapper;

import com.yrx.simple.life.eden.infrastructure.po.JourneyPo;
import java.util.List;

public interface JourneyPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    int insert(JourneyPo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    JourneyPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    List<JourneyPo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table journey
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    int updateByPrimaryKey(JourneyPo row);
}