package com.yrx.simple.life.eden.infrastructure.po;

import java.util.Date;

public class AntidotePo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.id
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.title
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.key
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.val
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private String val;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.remark
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.create_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.update_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column antidote.del_flag
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    private Byte delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.id
     *
     * @return the value of antidote.id
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.id
     *
     * @param id the value for antidote.id
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.title
     *
     * @return the value of antidote.title
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.title
     *
     * @param title the value for antidote.title
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.key
     *
     * @return the value of antidote.key
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.key
     *
     * @param key the value for antidote.key
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.val
     *
     * @return the value of antidote.val
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public String getVal() {
        return val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.val
     *
     * @param val the value for antidote.val
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setVal(String val) {
        this.val = val;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.remark
     *
     * @return the value of antidote.remark
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.remark
     *
     * @param remark the value for antidote.remark
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.create_time
     *
     * @return the value of antidote.create_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.create_time
     *
     * @param createTime the value for antidote.create_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.update_time
     *
     * @return the value of antidote.update_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.update_time
     *
     * @param updateTime the value for antidote.update_time
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column antidote.del_flag
     *
     * @return the value of antidote.del_flag
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column antidote.del_flag
     *
     * @param delFlag the value for antidote.del_flag
     *
     * @mbg.generated Thu Aug 04 22:09:11 CST 2022
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }
}