package com.yrx.simple.life.eden.infrastructure.po;

import java.util.Date;

public class JourneyPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.id
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.data_date
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private Date dataDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.summary
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.expected
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private String expected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.actual
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private String actual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.remark
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.del_flag
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private Byte delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.create_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column journey.update_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.id
     *
     * @return the value of journey.id
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.id
     *
     * @param id the value for journey.id
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.data_date
     *
     * @return the value of journey.data_date
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public Date getDataDate() {
        return dataDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.data_date
     *
     * @param dataDate the value for journey.data_date
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setDataDate(Date dataDate) {
        this.dataDate = dataDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.summary
     *
     * @return the value of journey.summary
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.summary
     *
     * @param summary the value for journey.summary
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.expected
     *
     * @return the value of journey.expected
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public String getExpected() {
        return expected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.expected
     *
     * @param expected the value for journey.expected
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setExpected(String expected) {
        this.expected = expected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.actual
     *
     * @return the value of journey.actual
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public String getActual() {
        return actual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.actual
     *
     * @param actual the value for journey.actual
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setActual(String actual) {
        this.actual = actual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.remark
     *
     * @return the value of journey.remark
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.remark
     *
     * @param remark the value for journey.remark
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.del_flag
     *
     * @return the value of journey.del_flag
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public Byte getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.del_flag
     *
     * @param delFlag the value for journey.del_flag
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.create_time
     *
     * @return the value of journey.create_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.create_time
     *
     * @param createTime the value for journey.create_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column journey.update_time
     *
     * @return the value of journey.update_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column journey.update_time
     *
     * @param updateTime the value for journey.update_time
     *
     * @mbg.generated Wed Aug 10 20:58:08 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}